<a href="https://colab.research.google.com/github/tanishachouhan019/Pandas-Data-Analysis-Lab/blob/main/Pandas_Data_Cleaning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment - Data Cleaning

Easy to Moderate Level

## Q1. Find Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})

Output:
    Name    Age
0  False  False
1  False   True
2   True  False

In [15]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})
df.isnull()

    Name    Age
0  False  False
1  False   True
2   True  False

## Q2. Count Total Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})

Output:
Name    1
Age     1

In [16]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,np.nan,25]
})
df.isnull().sum()

Name    1
Age     1
dtype: int64

## Q3. Fill Missing Age with 0

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})

Output:
   Name   Age
0  Aman  20.0
1   Raj   0.0

In [17]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,np.nan]
})
df.fillna(0)

   Name   Age
0  Aman  20.0
1   Raj   0.0

## Q4. Fill Missing City with 'Unknown'

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})

Output:
   Name     City
0  Aman   Bhopal
1   Raj  Unknown

In [18]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})
df.fillna("Unknown")

   Name     City
0  Aman   Bhopal
1   Raj  Unknown

## Q5. Remove Rows Having Null Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})

Output:
   Name  Age
0  Aman   20
1   Raj   25

In [19]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})
df.dropna()

   Name  Age
0  Aman   20
1   Raj   25

## Q6. Convert Age Column into Float

Input:
df = pd.DataFrame({"Age":[20,25,30]})

Output:
20.0, 25.0, 30.0

In [20]:
import pandas as pd
import numpy as np
df = pd.DataFrame({"Age":[20,25,30]})
df.astype(float)

    Age
0  20.0
1  25.0
2  30.0

## Q7. Replace Delhi with New Delhi

Input:
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})

Output:
New Delhi, Mumbai, New Delhi

In [21]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})
df.replace("Delhi","New Delhi")

        City
0  New Delhi
1     Mumbai
2  New Delhi

## Q8. Replace Score 88 with 100

Input:
df = pd.DataFrame({
    "Score":[88,90,88,75]
})

Output:
100,90,100,75

In [22]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Score":[88,90,88,75]
})
df.replace(88,100)

   Score
0    100
1     90
2    100
3     75

## Q9. Drop City Column

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})

Output:
   Name
0  Aman
1   Raj

In [23]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})
df.drop("City",axis=1)

   Name
0  Aman
1   Raj

## Q10. Drop Row at Index 1

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})

Output:
   Name
0  Aman
2  Riya

In [24]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})
df.drop(1,axis=0)

   Name
0  Aman
2  Riya

## Q11. Check Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
False, False, True

In [25]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})
df.duplicated()

0    False
1    False
2     True
dtype: bool

## Q12. Remove Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
   Name
0  Aman
1   Raj

In [26]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})
df.drop_duplicates()

   Name
0  Aman
1   Raj

## Q13. Mini Data Cleaning Task

Input:
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}

Task:
1. Fill missing Age with mean.
2. Remove duplicate rows.
3. Display final DataFrame.

In [27]:
import pandas as pd
import numpy as np
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}
df = pd.DataFrame(data)

In [28]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_2811/2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df

   Name        Age    City
0  Aman  20.000000  Bhopal
1   Raj  21.666667   Delhi
3  None  25.000000  Indore